// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Class } from "./Class";
import type { Scene } from "./Scene";

/**
 * What `class_ensure_active` resolves on boot: the active class AND the
 * active scene (healed to the class default when the pointer is stale).
 */
export type ActiveContext = { class: Class, scene: Scene, };
