// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where «Dagens time» gets its content.
 */
export type AgendaSource = "planner" | "manual";
