// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One planned activity inside one lesson-instance.
 */
export type AgendaItem = { id: string, date: string, periodId: string, text: string, 
/**
 * `None` = untimed; timed items derive start offsets by prefix sum.
 */
durationMin: number | null, done: boolean, sortIndex: number, };
