// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One agenda item in a per-lesson save.
 */
export type AgendaItemSpec = { id: string | null, text: string, durationMin: number | null, done: boolean, };
