// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend shows in the about/status line.
 */
export type AppInfo = { name: string, version: string, };
