// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BootFaultKind } from "./BootFaultKind";

/**
 * What the boot has to tell the teacher, held in managed state and read once
 * by the shell (`boot_fault`).
 *
 * It exists because the honest alternative was worse: returning `Err` from
 * `setup` stops the whole app, so the ONE thing that could explain the
 * problem — a window with a sentence in it — never appears. The shell boots
 * degraded instead (typed fallbacks where the shim has them, honest
 * rejections everywhere else) and puts this at the top of its chip.
 */
export type BootFault = { kind: BootFaultKind, 
/**
 * Where the file is. The sentence ENDS in it: "the file is untouched:
 * <path>" is what makes the promise checkable by the person reading it,
 * and what she can hand to whoever helps her.
 */
dbPath: string, 
/**
 * The migration version sqlx named, when it named one.
 *
 * DIAGNOSTIC ONLY, and deliberately not in any sentence: this is a schema
 * number (`0005_…sql` → 5), not an app version. "Install version 5 or
 * newer" would be a fabricated instruction — there is no SundayScreen 5.
 * The shell says "a newer SundayScreen" and leaves the number to the log.
 */
schemaVersion: number | null, };
