// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which boot failure happened — the one axis the shell's chip switches on.
 *
 * A UNIT enum on purpose. `BootFault` carries the path and the schema number
 * alongside it, so the frontend reads `fault.kind === "databaseTooNew"`
 * rather than digging through a nested tag (which is what an internally
 * tagged enum with a shared field would have cost).
 */
export type BootFaultKind = "databaseTooNew" | "schemaUpdateStopped" | "unreadable" | "startedEmpty" | "rescueFailed";
