// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of the checklist widget.
 */
export type ChecklistItem = { id: string, text: string, done: boolean, };
