// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of the checklist widget. Like [`ManualAgendaItem`], a line keeps
 * the keys a NEWER version wrote on it — edit with `{ ...item, done }`,
 * never by rebuilding the object.
 */
export type ChecklistItem = { id: string, text: string, done: boolean, };
