// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Class } from "./Class";
import type { Member } from "./Member";
import type { WidgetInstance } from "./WidgetInstance";

/**
 * Everything the frontend needs after a class switch, read in one command
 * so the swap is atomic from the shell's point of view.
 */
export type ClassSnapshot = { class: Class, members: Array<Member>, widgets: Array<WidgetInstance>, };
