// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One class row. Exported to TS as `Class`.
 */
export type Class = { id: string, name: string, sortIndex: number, createdAt: number, };
