// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverrideKind } from "./OverrideKind";

/**
 * A per-date shadow of one (date, period) cell.
 */
export type DateOverride = { id: string, 
/**
 * Local wall date, `YYYY-MM-DD`, minted by the frontend.
 */
date: string, periodId: string, kind: OverrideKind, classId: string | null, subject: string, sceneId: string | null, 
/**
 * «Prøve», «Tur til Bymarka» — shown alongside/instead of the subject.
 */
title: string, };
