// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverrideKind } from "./OverrideKind";

/**
 * A per-date shadow of one (date, period) cell.
 */
export type DateOverride = { id: string, 
/**
 * Local wall date, `YYYY-MM-DD`, minted by the frontend.
 */
date: string, periodId: string, kind: OverrideKind, classId: string | null, subject: string, sceneId: string | null, 
/**
 * «Prøve», «Tur til Bymarka» — shown alongside/instead of the subject.
 */
title: string, 
/**
 * The TRI-STATE the nullable column exists for: `None` inherits the
 * weekly slot's flag, `Some(true)` merges on this date alone,
 * `Some(false)` splits on this date alone.
 *
 * A row that carries this and nothing else is a FLAG CARRIER (see the
 * module header): its content resolves from the week, so a per-date
 * merge never forks the weekly plan.
 */
mergedWithNext: boolean | null, };
