// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgendaItem } from "./AgendaItem";
import type { LessonInfo } from "./LessonInfo";
import type { Period } from "./Period";

/**
 * One period of the resolved day.
 */
export type DayEntry = { period: Period, 
/**
 * `None`: a break, a free period, or a cancelled lesson.
 */
lesson: LessonInfo | null, agenda: Array<AgendaItem>, 
/**
 * RESOLVED, not stored: this entry is the HEAD of a double lesson that
 * runs on into the next lesson period. A stored flag with nowhere to go
 * (the day's last lesson period) never reaches this field.
 *
 * `#[ts(optional = nullable)]` on both this and [`Self::continuation`]:
 * the field is `#[serde(default)]`, i.e. its absence is a legal way to
 * say `false`, and saying so in the TypeScript type is what lets a
 * frontend written before double lessons existed keep compiling —
 * exactly the tolerance ADR-007 gives a widget config, applied to a
 * generated type.
 */
mergedWithNext?: boolean, 
/**
 * RESOLVED: this entry is the TAIL of a double lesson — its `lesson` was
 * copied from the head, and a view that lists lessons should fold it
 * into the head rather than draw it twice.
 */
continuation?: boolean, 
/**
 * The override ROW's own `merged_with_next`, RAW — not the resolved
 * answer above. It exists for exactly one writer: the day tab's
 * override editor rewrites the whole row (`planner_override_set` is a
 * replace), and a writer that cannot see the stored tri-state rewrites
 * it as «inherit» — which is how editing a title used to silently undo
 * «Slå sammen med neste i dag» (R6-funn F-R6-1). `None` covers both «no
 * row» and «row that inherits», deliberately: those two round-trip to
 * the same write, so one Option is exactly enough.
 */
overrideMergedWithNext?: boolean | null, };
