// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A day-level message («Husk gymtøy i morgen») shown by «Dagen i dag».
 */
export type DayNote = { id: string, date: string, body: string, sortIndex: number, };
