// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DayEntry } from "./DayEntry";
import type { DayNote } from "./DayNote";

/**
 * Everything the widgets and the banner need about one date.
 */
export type DayPlan = { date: string, weekday: number, entries: Array<DayEntry>, notes: Array<DayNote>, };
