// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The die's COLOUR FAMILY — the body tone a die is cut from. Serialised
 * lowercase; the spelling is persisted config vocabulary, so renaming a
 * variant is a broken database exactly like renaming a `kind`.
 *
 * Six families and no more, because the point is telling three dice apart
 * on a projector at eight metres, not offering a colour picker. The names
 * are the FAMILY, never a token: `--die-red` and its ink live in
 * `app/styles/tokens.css`, and the material ramp mixes from there.
 *
 * ⚠️ `Classic` is not «white». It is the warm off-white of a school die,
 * and it is the default because a teacher who never opens the appearance
 * panel must still get the die the widget has always drawn.
 */
export type DieColor = "classic" | "red" | "blue" | "green" | "gold" | "slate";
