// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The die's FINISH — how the same family is shaded, edged and lettered.
 * Serialised lowercase, same persisted-vocabulary rule as [`DieColor`].
 *
 * Colour and material are two axes ON PURPOSE (6 × 5, not 30 flat names):
 * «a red casino die» is how a teacher describes what she wants, and a flat
 * list would have made the panel a wall of thirty tiles nobody scans.
 */
export type DieMaterial = "ivory" | "casino" | "wood" | "metal" | "glass";
