// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from "./Member";

/**
 * One draw's answer.
 */
export type DrawResult = { member: Member, 
/**
 * How many are still undrawn in this round AFTER this draw (the whole
 * PRESENT class in repeat-allowed mode).
 */
remaining: number, 
/**
 * Did THIS draw start a new round (the previous one was complete)?
 */
reshuffled: boolean, };
