// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from "./Member";

/**
 * One draw's answer — one name, or several.
 */
export type DrawManyResult = { 
/**
 * The drawn pupils, in draw order. Always DISTINCT, and never more than
 * are present: asking for five in a class of four answers with four,
 * because there is no fifth different name to give.
 */
members: Array<Member>, 
/**
 * How many are still undrawn in this round AFTER this draw (the whole
 * PRESENT class in repeat-allowed mode).
 */
remaining: number, 
/**
 * Did THIS draw start a new round (the previous one was complete, or ran
 * out part-way through this draw)?
 */
reshuffled: boolean, };
