// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an export actually wrote. A RECEIPT rather than a bare path, because
 * there is now a second thing a teacher has to be told.
 *
 * The pictures ride along with the file (owner's decision, R6), and they are
 * the one part of a setup that can be too big to carry: the caps in
 * `sundayscreen_core::transfer` bound what any one file may hold. When a
 * board has more pictures than fit, the file is still written — a setup with
 * most of its pictures is worth having — and this receipt SAYS how many
 * stayed behind. The alternative is the shape this house refuses: a
 * «Lagret: …» chip over a file with holes in it, discovered on the other
 * machine where nothing can be done about it.
 */
export type ExportReceipt = { 
/**
 * Where it landed — the sentence the panel already showed.
 */
path: string, 
/**
 * Pictures written INTO the file. Worth saying out loud: this is the
 * number that makes the file heavier than a name list, and PRIVACY.md
 * treats it accordingly.
 */
images: number, 
/**
 * Pictures the board has and the file could not carry.
 */
imagesLeftOut: number, };
