// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the group generator counts. Serialised lowercase.
 */
export type GroupMode = "count" | "size";
