// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a picture fills its card. Serialised lowercase — part of the persisted
 * config vocabulary, so a renamed variant is a broken database.
 */
export type ImageFit = "contain" | "cover";
