// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportOutcome } from "./ImportOutcome";

/**
 * What to tell the teacher afterwards. Every field is meaningful for
 * `Imported` and zero/false for every refusal — nothing was written in those
 * cases, and the numbers must say so.
 */
export type ImportReceipt = { outcome: ImportOutcome, 
/**
 * Classes added.
 */
classes: number, 
/**
 * LIBRARY screens added. Class default screens are not counted here:
 * they arrive as part of their class, the way they do everywhere else.
 */
scenes: number, 
/**
 * Pupil names added, across all imported classes.
 */
members: number, 
/**
 * Did the school day (period template + weekly timetable) come along?
 */
plannerImported: boolean, 
/**
 * Did the file HAVE a school day that was skipped because this machine
 * already had one? Never true at the same time as `planner_imported`.
 */
plannerSkipped: boolean, 
/**
 * The `appVersion` the file names — diagnostics, and the one thing the
 * «Fila er laget med SundayScreen X» sentence needs. Empty when the file
 * was never read that far.
 */
fileAppVersion: string, 
/**
 * Pictures a screen in this file POINTS AT and this machine did not get:
 * the file was written by a build that did not carry pictures, or the
 * picture did not fit under the export's ceiling, or its bytes were not
 * a picture after all.
 *
 * A count rather than a silence, because the alternative is the shape
 * this house keeps refusing: a receipt saying «Importert» over screens
 * with holes in them, discovered mid-lesson. The affected cards say
 * «bildet mangler» on the board, and this number is what tells her
 * BEFORE she looks.
 *
 * `#[serde(default)]` is written for the reader rather than for serde —
 * this struct is Serialize-only, so nothing deserialises it — and says
 * the same thing the field's zero does: an older shell reading a newer
 * receipt is not a case this app has, and the honest value when nobody
 * counted is none.
 */
imagesSkipped: number, };
