// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an import ended. A UNIT enum, like `BootFaultKind` and for the same
 * reason: the panel switches on `receipt.outcome === "tooNew"` rather than
 * digging through a nested tag, and every variant is a DIFFERENT sentence to
 * a teacher.
 */
export type ImportOutcome = "cancelled" | "imported" | "notOurFile" | "tooNew" | "unreadable" | "tooLarge";
