// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The effective lesson in one period of one date, names joined in.
 */
export type LessonInfo = { classId: string | null, className: string | null, subject: string, sceneId: string | null, sceneName: string | null, title: string, 
/**
 * Did a date override produce this (or cancel it)?
 */
overridden: boolean, };
