// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a manual agenda (planner-free mode).
 */
export type ManualAgendaItem = { id: string, text: string, durationMin: number | null, done: boolean, };
