// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a manual agenda (planner-free mode).
 *
 * ADR-007 applies one level DOWN as well: keys a NEWER version wrote on an
 * individual LINE survive this build's load→save cycle. Keep the whole item
 * when you edit one (`{ ...item, done: true }`), never rebuild it field by
 * field — a rebuilt line drops what this build cannot see.
 */
export type ManualAgendaItem = { id: string, text: string, durationMin: number | null, done: boolean, };
