// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pupil row. Exported to TS as `Member`.
 */
export type Member = { id: string, name: string, sortIndex: number, };
