// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pupil row. Exported to TS as `Member`.
 */
export type Member = { id: string, name: string, sortIndex: number, 
/**
 * The local wall date this pupil was marked away, or `None`. "Away
 * today" is `absent_on == today` — a DATE STAMP, so yesterday's absence
 * expires by itself, with no reset job to miss a day (migration 0005).
 * Overwritten, never appended to: there is no attendance history here.
 */
absentOn: string | null, };
