// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A widget's place on the surface, normalised 0..1 per axis.
 */
export type NormRect = { x: number, y: number, w: number, h: number, };
