// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day note in a per-date save.
 */
export type NoteSpec = { id: string | null, body: string, };
