// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverrideKind } from "./OverrideKind";

/**
 * One date override's content.
 */
export type OverrideSpec = { kind: OverrideKind, classId: string | null, subject: string, sceneId: string | null, title: string, };
