// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodKind } from "./PeriodKind";

/**
 * One period in a template save. `id = None` mints a fresh row; `Some`
 * keeps the id so the week/agendas hanging off it survive a re-timing.
 */
export type PeriodSpec = { id: string | null, label: string, startMin: number, endMin: number, kind: PeriodKind, };
