// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodKind } from "./PeriodKind";

/**
 * A slot in the school day's template (defined once, applies Mon–Fri).
 */
export type Period = { id: string, label: string, startMin: number, endMin: number, kind: PeriodKind, sortIndex: number, };
