// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One scene row. `class_id = None` is a GLOBAL library scene; `Some` is a
 * class's default screen. Exported to TS as `Scene`.
 */
export type Scene = { id: string, classId: string | null, name: string, sortIndex: number, createdAt: number, };
