// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneTheme } from "./SceneTheme";

/**
 * One scene row. `class_id = None` is a GLOBAL library scene; `Some` is a
 * class's default screen. Exported to TS as `Scene`.
 */
export type Scene = { id: string, classId: string | null, name: string, sortIndex: number, createdAt: number, 
/**
 * The BACKDROP the screen is drawn on (migration 0006). Stored as TEXT
 * and read leniently, so an unknown spelling degrades to
 * [`SceneTheme::Standard`] instead of failing the row.
 */
theme: SceneTheme, };
