// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The backdrop a scene is drawn on.
 *
 * Serialised lowercase, and the spellings are PERSISTED VOCABULARY: they sit
 * in the `scene.theme` column and in a transfer file, so renaming a variant
 * is a broken database exactly like renaming a widget `kind` — the same rule
 * `layout::DieColor` carries.
 *
 * ⚠️ `Kjolig` has no `ø`. The stored word is ASCII on purpose — the DISPLAY
 * name «Kjølig» lives in the i18n catalogue (`theme.name.kjolig`), and the
 * two must never be confused for one another.
 */
export type SceneTheme = "standard" | "papir" | "varm" | "kjolig" | "tavle";
