// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a screen is still used in the PLAN — the two numbers behind «denne
 * skjermen brukes i N timer».
 *
 * Two fields rather than one total: they are different sentences to a
 * teacher (a weekly cell repeats every week; a date override happens once),
 * and adding them here would take that choice away from the frontend.
 */
export type SceneUsage = { 
/**
 * Cells in the recurring weekly timetable pointing at this screen.
 */
weekSlots: number, 
/**
 * Date overrides pointing at it on `today` or later. The past is not
 * counted: it cannot be affected by a deletion made now.
 */
futureOverrides: number, };
