// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateChannel } from "./UpdateChannel";
import type { WindowState } from "./WindowState";

/**
 * The complete settings model.
 *
 * Every field carries `#[serde(default)]` so a partial or older JSON blob
 * deserialises by filling in the per-field default. Numeric ranges are
 * enforced separately by [`Settings::validate`], which every load/save runs.
 */
export type Settings = { 
/**
 * UI language code (e.g. `"no"`). `None` means "follow the OS" — the
 * frontend resolves that to an active locale.
 */
language: string | null, 
/**
 * The class whose name list + layout is on screen. `None` until the first
 * class exists; the frontend then opens the manage panel.
 */
activeClassId: string | null, 
/**
 * Snap widget edges to the surface and to siblings while dragging.
 */
snapEnabled: boolean, 
/**
 * Saved window geometry, or `None` for the config default.
 */
window: WindowState | null, 
/**
 * Which release feed this install follows.
 */
updateChannel: UpdateChannel, };
