// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateChannel } from "./UpdateChannel";
import type { WindowState } from "./WindowState";

/**
 * The complete settings model.
 *
 * Every field carries `#[serde(default)]` so a partial or older JSON blob
 * deserialises by filling in the per-field default. Numeric ranges are
 * enforced separately by [`Settings::validate`], which every load/save runs.
 */
export type Settings = { 
/**
 * UI language code (e.g. `"no"`). `None` means "follow the OS" — the
 * frontend resolves that to an active locale.
 */
language: string | null, 
/**
 * The class whose name list + layout is on screen. `None` until the first
 * class exists; the frontend then opens the manage panel.
 */
activeClassId: string | null, 
/**
 * The scene on screen: a global library scene, or the active class's
 * default. `None`/invalid heals to the class default (Runde 2).
 */
activeSceneId: string | null, 
/**
 * Snap widget edges to the surface and to siblings while dragging.
 */
snapEnabled: boolean, 
/**
 * Saved window geometry, or `None` for the config default.
 */
window: WindowState | null, 
/**
 * Which release feed this install follows.
 */
updateChannel: UpdateChannel, 
/**
 * Fetch a found update in the background and install it when the app
 * CLOSES. On by default (ADR-014): a classroom machine nobody
 * administers is safer up to date than pinned to whatever shipped on it,
 * and the install is deferred to the one moment where a restart costs
 * nothing. Turning it off leaves the marker and the manual button
 * exactly as they were.
 *
 * `lenient_true`, not `lenient`: `bool::default()` is `false`, and a
 * value we could not read must never be recorded as "the teacher turned
 * automatic updates off".
 */
autoUpdate: boolean, 
/**
 * Opt-in: switch class+scene automatically when a planned lesson
 * starts. Off by default — the banner suggests, the teacher decides.
 */
autoSwitchScenes: boolean, 
/**
 * The SCHOOL's lesson length in minutes — what one press of «Legg til
 * time» spans. Schools run 30-, 45- or 60-minute lessons and the choice
 * is a fact about the school, not about one editing session, which is
 * why it lives here and not in component state. 45 is the default the
 * button has always had.
 *
 * `lenient_lesson_minutes`, not `lenient`: `u16::default()` is 0, and a
 * value we could not read must never become «0-minutters skoletime» —
 * nor the clamp floor pretending someone chose it (the B#7 lesson:
 * garbage and absent must land on the SAME documented default).
 */
lessonMinutes: number, };
