// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One weekly cell's content.
 */
export type SlotSpec = { classId: string | null, subject: string, sceneId: string | null, };
