// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One picture, on its way to the webview.
 */
export type StoredImage = { 
/**
 * `image/png`, `image/jpeg` or `image/webp` — read off the stored bytes,
 * never off the file name. The page needs it to build a `Blob` the
 * browser will render.
 */
mime: string, 
/**
 * The picture, base64. Big — a 10 MiB photograph crosses as ~13 MiB of
 * JSON — and that is accepted deliberately: it happens ONCE per picture
 * per boot, because `app/widgets/image/blob-cache.ts` holds the object
 * URL for as long as a card is showing it.
 */
bytesBase64: string, };
