// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text alignment inside the text widget.
 */
export type TextAlign = "left" | "center" | "right";
