// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The timer's EPHEMERAL state. Deliberately not persisted: a restart
 * mid-countdown shows the configured duration again, honestly.
 */
export type TimerState = { "phase": "idle" } | { "phase": "running", targetEpochMs: number, } | { "phase": "paused", remainingMs: number, } | { "phase": "finished", atEpochMs: number, } | { "phase": "swRunning", startedEpochMs: number, accumulatedMs: number, } | { "phase": "swPaused", accumulatedMs: number, };
