// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way the timer counts. Serialised lowercase — part of the persisted
 * config vocabulary.
 */
export type TimerMode = "countdown" | "stopwatch";
