// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which release feed this install follows. The lowercase tag IS the feed's
 * path segment (`/v1/update/sundayscreen/{stable|beta}`) — a renamed
 * variant is a renamed live URL.
 */
export type UpdateChannel = "stable" | "beta";
