// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One cell of the recurring weekly timetable: weekday × lesson-period.
 */
export type WeekSlot = { id: string, 
/**
 * ISO weekday, 1 (Monday) ..= 5 (Friday).
 */
weekday: number, periodId: string, classId: string | null, subject: string, 
/**
 * `None` → the class's default scene at switch time.
 */
sceneId: string | null, 
/**
 * Does this lesson run on into the next lesson period, every week?
 *
 * `#[serde(default)]` so a setup file (or a row) written before
 * migration 0007 reads as an ordinary single lesson rather than failing.
 */
mergedWithNext: boolean, };
