// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One cell of the recurring weekly timetable: weekday × lesson-period.
 */
export type WeekSlot = { id: string, 
/**
 * ISO weekday, 1 (Monday) ..= 5 (Friday).
 */
weekday: number, periodId: string, classId: string | null, subject: string, 
/**
 * `None` → the class's default scene at switch time.
 */
sceneId: string | null, };
