// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAlign } from "./TextAlign";

/**
 * Per-kind widget configuration. The serde tag IS the `kind` column value —
 * a renamed variant is a broken database.
 *
 * Adding a widget kind = one variant here (+ default + clamp arm) + one
 * frontend folder + one registry line. Nothing else.
 */
export type WidgetConfig = { "kind": "text", content: string, fontScale: number, align: TextAlign, };
