// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgendaSource } from "./AgendaSource";
import type { ChecklistItem } from "./ChecklistItem";
import type { ClockFace } from "./ClockFace";
import type { GroupMode } from "./GroupMode";
import type { ManualAgendaItem } from "./ManualAgendaItem";
import type { TextAlign } from "./TextAlign";
import type { TimerMode } from "./TimerMode";
import type { TrafficColor } from "./TrafficColor";
import type { WorkMode } from "./WorkMode";

/**
 * Per-kind widget configuration. The serde tag IS the `kind` column value —
 * a renamed variant is a broken database.
 *
 * Adding a widget kind = one variant here (+ default + clamp arm) + one
 * frontend folder + one registry line. Nothing else.
 *
 * Every variant carries a flattened `extra` map (ADR-007): fields a NEWER
 * version wrote into a KNOWN kind survive this build's load→save cycle
 * instead of being silently dropped. `#[ts(skip)]` keeps the TS types
 * unchanged — the webview receives the unknown keys inline and its
 * `{ ...cfg }` spreads carry them back untouched.
 *
 * ADR-007 covered unknown FIELDS; unknown VALUES fell straight through it.
 * An enum-valued field this build cannot spell now costs THAT FIELD ONLY —
 * it reads as the field's default, and everything beside it survives.
 */
export type WidgetConfig = { "kind": "text", content: string, fontScale: number, align: TextAlign, } | { "kind": "clock", face: ClockFace, showSeconds: boolean, showDate: boolean, } | { "kind": "timer", durationMs: number, warnAtMs: number, soundOn: boolean, mode: TimerMode, } | { "kind": "namepicker", noRepeat: boolean, lastDrawn: string | null, 
/**
 * The whole draw, in draw order. Empty in a config written before
 * multi-draw existed — the widget falls back to `last_drawn` there,
 * which is what keeps promise 2 across the upgrade.
 */
lastDrawnMany: Array<string>, 
/**
 * How many names the next draw asks for, 1..=[`PICK_N_MAX`].
 */
drawCount: number, } | { "kind": "groups", mode: GroupMode, n: number, 
/**
 * The last split, as NAMES — restored on boot so the class walks in
 * to the same groups the projector showed yesterday.
 */
lastResult: Array<Array<string>>, } | { "kind": "dice", count: number, faces: number, lastRoll: Array<number>, } | { "kind": "trafficlight", active: TrafficColor, } | { "kind": "worksymbol", mode: WorkMode, } | { "kind": "agenda", source: AgendaSource, showTimes: boolean, manualItems: Array<ManualAgendaItem>, pinnedItemId: string | null, } | { "kind": "deadline", title: string, targetEpochMs: number, showHours: boolean, } | { "kind": "checklist", items: Array<ChecklistItem>, } | { "kind": "today", showLessons: boolean, showNotes: boolean, };
