// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NormRect } from "./NormRect";
import type { WidgetConfig } from "./WidgetConfig";

/**
 * One widget on a class's screen.
 */
export type WidgetInstance = { id: string, rect: NormRect, 
/**
 * Stacking order; re-indexed 0..n by [`clamp_layout`]. i64 would map to
 * `bigint` in TS; force `number` (z never leaves 0..n).
 */
z: number, config: WidgetConfig, };
