// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgendaSource } from "./AgendaSource";
import type { ChecklistItem } from "./ChecklistItem";
import type { ClockFace } from "./ClockFace";
import type { DieColor } from "./DieColor";
import type { DieMaterial } from "./DieMaterial";
import type { GroupMode } from "./GroupMode";
import type { ImageFit } from "./ImageFit";
import type { ManualAgendaItem } from "./ManualAgendaItem";
import type { TextAlign } from "./TextAlign";
import type { TimerMode } from "./TimerMode";
import type { TrafficColor } from "./TrafficColor";
import type { WorkMode } from "./WorkMode";

/**
 * Per-kind widget configuration. The serde tag IS the `kind` column value —
 * a renamed variant is a broken database.
 *
 * Adding a widget kind = one variant here (+ default + clamp arm) + one
 * frontend folder + one registry line. Nothing else.
 *
 * Every variant carries a flattened `extra` map (ADR-007): fields a NEWER
 * version wrote into a KNOWN kind survive this build's load→save cycle
 * instead of being silently dropped. `#[ts(skip)]` keeps the TS types
 * unchanged — the webview receives the unknown keys inline and its
 * `{ ...cfg }` spreads carry them back untouched.
 *
 * ADR-007 covered unknown FIELDS; unknown VALUES fell straight through it.
 * An enum-valued field this build cannot spell now costs THAT FIELD ONLY —
 * it reads as the field's default, and everything beside it survives.
 */
export type WidgetConfig = { "kind": "text", content: string, fontScale: number, align: TextAlign, } | { "kind": "clock", face: ClockFace, showSeconds: boolean, showDate: boolean, } | { "kind": "timer", durationMs: number, warnAtMs: number, soundOn: boolean, mode: TimerMode, } | { "kind": "namepicker", noRepeat: boolean, lastDrawn: string | null, 
/**
 * The whole draw, in draw order. Empty in a config written before
 * multi-draw existed — the widget falls back to `last_drawn` there,
 * which is what keeps promise 2 across the upgrade.
 */
lastDrawnMany: Array<string>, 
/**
 * How many names the next draw asks for, 1..=[`PICK_N_MAX`].
 */
drawCount: number, } | { "kind": "groups", mode: GroupMode, n: number, 
/**
 * The last split, as NAMES — restored on boot so the class walks in
 * to the same groups the projector showed yesterday.
 */
lastResult: Array<Array<string>>, } | { "kind": "dice", count: number, faces: number, 
/**
 * The REAL ten-sided classroom die reads 0–9, not 1–10 (opposite
 * faces sum to 9): same body, the «10» face printed as a «0». Only
 * the d10 carries this flag — `normalize` clears it on every other
 * type, so the pair (faces, zero_based) IS the die type and there is
 * no such thing as a zero-based d6 in a stored layout.
 *
 * Downgrade accounting, same family as the `faces` note above: on a
 * pre-0.5.1 build the flag itself survives in `extra`, but that
 * build's roll clamp pins values to 1..=faces, so a persisted 0 is
 * rewritten as a 1 — value distortion, not data loss.
 */
zeroBased: boolean, lastRoll: Array<number>, 
/**
 * The colour family and the finish — APPEARANCE, not protocol. A
 * roll stays true across a re-colour, which is why neither field
 * clears `last_roll` the way `faces` does.
 */
color: DieColor, material: DieMaterial, } | { "kind": "trafficlight", active: TrafficColor, } | { "kind": "worksymbol", mode: WorkMode, } | { "kind": "agenda", source: AgendaSource, showTimes: boolean, manualItems: Array<ManualAgendaItem>, pinnedItemId: string | null, } | { "kind": "deadline", title: string, targetEpochMs: number, showHours: boolean, } | { "kind": "checklist", items: Array<ChecklistItem>, } | { "kind": "today", showLessons: boolean, showNotes: boolean, } | { "kind": "link", title: string, url: string, showQr: boolean, } | { "kind": "image", 
/**
 * The stored file's id — `""` means "not set". Shape-clamped to the
 * UUID alphabet so a path separator is not merely rejected later but
 * unrepresentable here.
 */
imageId: string, fit: ImageFit, caption: string, };
