// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The saved main-window geometry, restored on boot. `None` in
 * [`Settings::window`] means "never saved — use the tauri.conf.json default".
 */
export type WindowState = { 
/**
 * Outer position, logical pixels. May be negative on multi-monitor rigs.
 */
x: number, y: number, 
/**
 * Outer size, logical pixels. Clamped by [`Settings::validate`].
 */
w: number, h: number, 
/**
 * Was the app in fullscreen when it closed?
 */
fullscreen: boolean, };
