// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The work-mode symbols. Serialised lowercase.
 */
export type WorkMode = "silent" | "whisper" | "collaborate" | "raisehand";
